/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface OffsetHelperInterface extends ethers.utils.Interface {
  functions: {
    "autoOffsetExactInETH(address,address[])": FunctionFragment;
    "autoOffsetExactInToken(address,uint256,address,address[])": FunctionFragment;
    "autoOffsetExactOutETH(address,uint256,address[])": FunctionFragment;
    "autoOffsetExactOutToken(address,address,uint256,address[])": FunctionFragment;
    "autoOffsetPoolToken(address,uint256)": FunctionFragment;
    "autoRedeem(address,uint256)": FunctionFragment;
    "autoRetire(address[],uint256[])": FunctionFragment;
    "balances(address,address)": FunctionFragment;
    "baseERC20()": FunctionFragment;
    "baseToken()": FunctionFragment;
    "calculateExpectedPoolTokenForETH(uint256,address,address[])": FunctionFragment;
    "calculateExpectedPoolTokenForToken(address,uint256,address,address[])": FunctionFragment;
    "calculateNeededETHAmount(address,uint256,address[])": FunctionFragment;
    "calculateNeededTokenAmount(address,address,uint256,address[])": FunctionFragment;
    "contractRegistryAddress()": FunctionFragment;
    "deleteEligibleTokenAddress(string)": FunctionFragment;
    "deposit(address,uint256)": FunctionFragment;
    "dexRouterAddress()": FunctionFragment;
    "eligibleTokenAddresses(string)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setEligibleTokenAddress(string,address)": FunctionFragment;
    "setToucanContractRegistry(address)": FunctionFragment;
    "swapExactInETH(address,address[])": FunctionFragment;
    "swapExactInToken(address,uint256,address,address[])": FunctionFragment;
    "swapExactOutETH(address,uint256,address[])": FunctionFragment;
    "swapExactOutToken(address,address,uint256,address[])": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "withdraw(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "autoOffsetExactInETH",
    values: [string, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "autoOffsetExactInToken",
    values: [string, BigNumberish, string, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "autoOffsetExactOutETH",
    values: [string, BigNumberish, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "autoOffsetExactOutToken",
    values: [string, string, BigNumberish, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "autoOffsetPoolToken",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "autoRedeem",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "autoRetire",
    values: [string[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "balances",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "baseERC20", values?: undefined): string;
  encodeFunctionData(functionFragment: "baseToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "calculateExpectedPoolTokenForETH",
    values: [BigNumberish, string, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateExpectedPoolTokenForToken",
    values: [string, BigNumberish, string, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateNeededETHAmount",
    values: [string, BigNumberish, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateNeededTokenAmount",
    values: [string, string, BigNumberish, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "contractRegistryAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deleteEligibleTokenAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dexRouterAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "eligibleTokenAddresses",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setEligibleTokenAddress",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setToucanContractRegistry",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "swapExactInETH",
    values: [string, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "swapExactInToken",
    values: [string, BigNumberish, string, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "swapExactOutETH",
    values: [string, BigNumberish, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "swapExactOutToken",
    values: [string, string, BigNumberish, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "autoOffsetExactInETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "autoOffsetExactInToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "autoOffsetExactOutETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "autoOffsetExactOutToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "autoOffsetPoolToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "autoRedeem", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "autoRetire", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balances", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "baseERC20", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "baseToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateExpectedPoolTokenForETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateExpectedPoolTokenForToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateNeededETHAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateNeededTokenAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contractRegistryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteEligibleTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "dexRouterAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eligibleTokenAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEligibleTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setToucanContractRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapExactInETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapExactInToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapExactOutETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapExactOutToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "Initialized(uint8)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Redeemed(address,address,address[],uint256[])": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Redeemed"): EventFragment;
}

export type InitializedEvent = TypedEvent<[number] & { version: number }>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export type RedeemedEvent = TypedEvent<
  [string, string, string[], BigNumber[]] & {
    who: string;
    poolToken: string;
    tco2s: string[];
    amounts: BigNumber[];
  }
>;

export class OffsetHelper extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: OffsetHelperInterface;

  functions: {
    autoOffsetExactInETH(
      _poolToken: string,
      _customPath: string[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    autoOffsetExactInToken(
      _fromToken: string,
      _amountToSwap: BigNumberish,
      _poolToken: string,
      _customPath: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    autoOffsetExactOutETH(
      _poolToken: string,
      _amountToOffset: BigNumberish,
      _customPath: string[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    autoOffsetExactOutToken(
      _depositedToken: string,
      _poolToken: string,
      _amountToOffset: BigNumberish,
      _customPath: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    autoOffsetPoolToken(
      _poolToken: string,
      _amountToOffset: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    autoRedeem(
      _fromToken: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    autoRetire(
      _tco2s: string[],
      _amounts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    balances(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    baseERC20(overrides?: CallOverrides): Promise<[string]>;

    baseToken(overrides?: CallOverrides): Promise<[string]>;

    calculateExpectedPoolTokenForETH(
      _fromETHAmount: BigNumberish,
      _toToken: string,
      _customPath: string[],
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    calculateExpectedPoolTokenForToken(
      _fromToken: string,
      _fromAmount: BigNumberish,
      _toToken: string,
      _customPath: string[],
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    calculateNeededETHAmount(
      _toToken: string,
      _toAmount: BigNumberish,
      _customPath: string[],
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    calculateNeededTokenAmount(
      _fromToken: string,
      _toToken: string,
      _toAmount: BigNumberish,
      _customPath: string[],
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    contractRegistryAddress(overrides?: CallOverrides): Promise<[string]>;

    deleteEligibleTokenAddress(
      _tokenSymbol: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deposit(
      _erc20Addr: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    dexRouterAddress(overrides?: CallOverrides): Promise<[string]>;

    eligibleTokenAddresses(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setEligibleTokenAddress(
      _tokenSymbol: string,
      _address: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setToucanContractRegistry(
      _address: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapExactInETH(
      _toToken: string,
      _customPath: string[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapExactInToken(
      _fromToken: string,
      _fromAmount: BigNumberish,
      _toToken: string,
      _customPath: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapExactOutETH(
      _toToken: string,
      _toAmount: BigNumberish,
      _customPath: string[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapExactOutToken(
      _fromToken: string,
      _toToken: string,
      _toAmount: BigNumberish,
      _customPath: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdraw(
      _erc20Addr: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  autoOffsetExactInETH(
    _poolToken: string,
    _customPath: string[],
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  autoOffsetExactInToken(
    _fromToken: string,
    _amountToSwap: BigNumberish,
    _poolToken: string,
    _customPath: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  autoOffsetExactOutETH(
    _poolToken: string,
    _amountToOffset: BigNumberish,
    _customPath: string[],
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  autoOffsetExactOutToken(
    _depositedToken: string,
    _poolToken: string,
    _amountToOffset: BigNumberish,
    _customPath: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  autoOffsetPoolToken(
    _poolToken: string,
    _amountToOffset: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  autoRedeem(
    _fromToken: string,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  autoRetire(
    _tco2s: string[],
    _amounts: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  balances(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  baseERC20(overrides?: CallOverrides): Promise<string>;

  baseToken(overrides?: CallOverrides): Promise<string>;

  calculateExpectedPoolTokenForETH(
    _fromETHAmount: BigNumberish,
    _toToken: string,
    _customPath: string[],
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  calculateExpectedPoolTokenForToken(
    _fromToken: string,
    _fromAmount: BigNumberish,
    _toToken: string,
    _customPath: string[],
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  calculateNeededETHAmount(
    _toToken: string,
    _toAmount: BigNumberish,
    _customPath: string[],
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  calculateNeededTokenAmount(
    _fromToken: string,
    _toToken: string,
    _toAmount: BigNumberish,
    _customPath: string[],
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  contractRegistryAddress(overrides?: CallOverrides): Promise<string>;

  deleteEligibleTokenAddress(
    _tokenSymbol: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deposit(
    _erc20Addr: string,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  dexRouterAddress(overrides?: CallOverrides): Promise<string>;

  eligibleTokenAddresses(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setEligibleTokenAddress(
    _tokenSymbol: string,
    _address: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setToucanContractRegistry(
    _address: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapExactInETH(
    _toToken: string,
    _customPath: string[],
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapExactInToken(
    _fromToken: string,
    _fromAmount: BigNumberish,
    _toToken: string,
    _customPath: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapExactOutETH(
    _toToken: string,
    _toAmount: BigNumberish,
    _customPath: string[],
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapExactOutToken(
    _fromToken: string,
    _toToken: string,
    _toAmount: BigNumberish,
    _customPath: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdraw(
    _erc20Addr: string,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    autoOffsetExactInETH(
      _poolToken: string,
      _customPath: string[],
      overrides?: CallOverrides
    ): Promise<
      [string[], BigNumber[]] & { tco2s: string[]; amounts: BigNumber[] }
    >;

    autoOffsetExactInToken(
      _fromToken: string,
      _amountToSwap: BigNumberish,
      _poolToken: string,
      _customPath: string[],
      overrides?: CallOverrides
    ): Promise<
      [string[], BigNumber[]] & { tco2s: string[]; amounts: BigNumber[] }
    >;

    autoOffsetExactOutETH(
      _poolToken: string,
      _amountToOffset: BigNumberish,
      _customPath: string[],
      overrides?: CallOverrides
    ): Promise<
      [string[], BigNumber[]] & { tco2s: string[]; amounts: BigNumber[] }
    >;

    autoOffsetExactOutToken(
      _depositedToken: string,
      _poolToken: string,
      _amountToOffset: BigNumberish,
      _customPath: string[],
      overrides?: CallOverrides
    ): Promise<
      [string[], BigNumber[]] & { tco2s: string[]; amounts: BigNumber[] }
    >;

    autoOffsetPoolToken(
      _poolToken: string,
      _amountToOffset: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string[], BigNumber[]] & { tco2s: string[]; amounts: BigNumber[] }
    >;

    autoRedeem(
      _fromToken: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string[], BigNumber[]] & { tco2s: string[]; amounts: BigNumber[] }
    >;

    autoRetire(
      _tco2s: string[],
      _amounts: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    balances(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    baseERC20(overrides?: CallOverrides): Promise<string>;

    baseToken(overrides?: CallOverrides): Promise<string>;

    calculateExpectedPoolTokenForETH(
      _fromETHAmount: BigNumberish,
      _toToken: string,
      _customPath: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateExpectedPoolTokenForToken(
      _fromToken: string,
      _fromAmount: BigNumberish,
      _toToken: string,
      _customPath: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateNeededETHAmount(
      _toToken: string,
      _toAmount: BigNumberish,
      _customPath: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateNeededTokenAmount(
      _fromToken: string,
      _toToken: string,
      _toAmount: BigNumberish,
      _customPath: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    contractRegistryAddress(overrides?: CallOverrides): Promise<string>;

    deleteEligibleTokenAddress(
      _tokenSymbol: string,
      overrides?: CallOverrides
    ): Promise<void>;

    deposit(
      _erc20Addr: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    dexRouterAddress(overrides?: CallOverrides): Promise<string>;

    eligibleTokenAddresses(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setEligibleTokenAddress(
      _tokenSymbol: string,
      _address: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setToucanContractRegistry(
      _address: string,
      overrides?: CallOverrides
    ): Promise<void>;

    swapExactInETH(
      _toToken: string,
      _customPath: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapExactInToken(
      _fromToken: string,
      _fromAmount: BigNumberish,
      _toToken: string,
      _customPath: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapExactOutETH(
      _toToken: string,
      _toAmount: BigNumberish,
      _customPath: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    swapExactOutToken(
      _fromToken: string,
      _toToken: string,
      _toAmount: BigNumberish,
      _customPath: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    withdraw(
      _erc20Addr: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Initialized(uint8)"(
      version?: null
    ): TypedEventFilter<[number], { version: number }>;

    Initialized(
      version?: null
    ): TypedEventFilter<[number], { version: number }>;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    "Redeemed(address,address,address[],uint256[])"(
      who?: null,
      poolToken?: null,
      tco2s?: null,
      amounts?: null
    ): TypedEventFilter<
      [string, string, string[], BigNumber[]],
      { who: string; poolToken: string; tco2s: string[]; amounts: BigNumber[] }
    >;

    Redeemed(
      who?: null,
      poolToken?: null,
      tco2s?: null,
      amounts?: null
    ): TypedEventFilter<
      [string, string, string[], BigNumber[]],
      { who: string; poolToken: string; tco2s: string[]; amounts: BigNumber[] }
    >;
  };

  estimateGas: {
    autoOffsetExactInETH(
      _poolToken: string,
      _customPath: string[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    autoOffsetExactInToken(
      _fromToken: string,
      _amountToSwap: BigNumberish,
      _poolToken: string,
      _customPath: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    autoOffsetExactOutETH(
      _poolToken: string,
      _amountToOffset: BigNumberish,
      _customPath: string[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    autoOffsetExactOutToken(
      _depositedToken: string,
      _poolToken: string,
      _amountToOffset: BigNumberish,
      _customPath: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    autoOffsetPoolToken(
      _poolToken: string,
      _amountToOffset: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    autoRedeem(
      _fromToken: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    autoRetire(
      _tco2s: string[],
      _amounts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    balances(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    baseERC20(overrides?: CallOverrides): Promise<BigNumber>;

    baseToken(overrides?: CallOverrides): Promise<BigNumber>;

    calculateExpectedPoolTokenForETH(
      _fromETHAmount: BigNumberish,
      _toToken: string,
      _customPath: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateExpectedPoolTokenForToken(
      _fromToken: string,
      _fromAmount: BigNumberish,
      _toToken: string,
      _customPath: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateNeededETHAmount(
      _toToken: string,
      _toAmount: BigNumberish,
      _customPath: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateNeededTokenAmount(
      _fromToken: string,
      _toToken: string,
      _toAmount: BigNumberish,
      _customPath: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    contractRegistryAddress(overrides?: CallOverrides): Promise<BigNumber>;

    deleteEligibleTokenAddress(
      _tokenSymbol: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deposit(
      _erc20Addr: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    dexRouterAddress(overrides?: CallOverrides): Promise<BigNumber>;

    eligibleTokenAddresses(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setEligibleTokenAddress(
      _tokenSymbol: string,
      _address: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setToucanContractRegistry(
      _address: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapExactInETH(
      _toToken: string,
      _customPath: string[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapExactInToken(
      _fromToken: string,
      _fromAmount: BigNumberish,
      _toToken: string,
      _customPath: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapExactOutETH(
      _toToken: string,
      _toAmount: BigNumberish,
      _customPath: string[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapExactOutToken(
      _fromToken: string,
      _toToken: string,
      _toAmount: BigNumberish,
      _customPath: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdraw(
      _erc20Addr: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    autoOffsetExactInETH(
      _poolToken: string,
      _customPath: string[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    autoOffsetExactInToken(
      _fromToken: string,
      _amountToSwap: BigNumberish,
      _poolToken: string,
      _customPath: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    autoOffsetExactOutETH(
      _poolToken: string,
      _amountToOffset: BigNumberish,
      _customPath: string[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    autoOffsetExactOutToken(
      _depositedToken: string,
      _poolToken: string,
      _amountToOffset: BigNumberish,
      _customPath: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    autoOffsetPoolToken(
      _poolToken: string,
      _amountToOffset: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    autoRedeem(
      _fromToken: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    autoRetire(
      _tco2s: string[],
      _amounts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    balances(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    baseERC20(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    baseToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    calculateExpectedPoolTokenForETH(
      _fromETHAmount: BigNumberish,
      _toToken: string,
      _customPath: string[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calculateExpectedPoolTokenForToken(
      _fromToken: string,
      _fromAmount: BigNumberish,
      _toToken: string,
      _customPath: string[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calculateNeededETHAmount(
      _toToken: string,
      _toAmount: BigNumberish,
      _customPath: string[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calculateNeededTokenAmount(
      _fromToken: string,
      _toToken: string,
      _toAmount: BigNumberish,
      _customPath: string[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    contractRegistryAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deleteEligibleTokenAddress(
      _tokenSymbol: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deposit(
      _erc20Addr: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    dexRouterAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    eligibleTokenAddresses(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setEligibleTokenAddress(
      _tokenSymbol: string,
      _address: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setToucanContractRegistry(
      _address: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapExactInETH(
      _toToken: string,
      _customPath: string[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapExactInToken(
      _fromToken: string,
      _fromAmount: BigNumberish,
      _toToken: string,
      _customPath: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapExactOutETH(
      _toToken: string,
      _toAmount: BigNumberish,
      _customPath: string[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapExactOutToken(
      _fromToken: string,
      _toToken: string,
      _toAmount: BigNumberish,
      _customPath: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdraw(
      _erc20Addr: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
